# Generated by Django 2.0.4 on 2018-10-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('0', 'Masculino'), ('1', 'Feminino'), ('2', 'Indefinido')], max_length=1)),
                ('cor', models.CharField(choices=[('0', 'Negro'), ('1', 'Branco'), ('2', 'Amarelo'), ('3', 'Pardo')], max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('datadenacimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
    ]
